# bobthehamster/ohrrpgce-bin
# A package containing pre-compiled ohrrpgce wip branch binaries
# (These are only current up to the time the image was built/pushed)

FROM bobthehamster/ohrrpgce-build-env

WORKDIR /ohrrpgce
RUN ./compile_ohrrpgce_nightly_inside_docker.sh
