# bobthehamster/ohrrpgce-bin
# A package containing pre-compiled ohrrpgce wip branch binaries
# (These are only current up to the time the image was built/pushed)

FROM bobthehamster/ohrrpgce-build-env

# Copy over the script for compiling the latest nightly
COPY compile_ohrrpgce_nightly_inside_docker.sh /ohrrpgce/

WORKDIR /ohrrpgce
#RUN ./compile_ohrrpgce_nightly_inside_docker.sh
